theme: jekyll-theme-dinky

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: KnowDo
subtitle: We Know and We Do
description:
author: Xu Yi
language:
timezone: Asia/Shanghai
